import type { PublicSportsChannel } from "./types.js";

type Seed = readonly [
  id: string,
  name: string,
  country: string,
  language: string,
  sports: readonly string[],
  officialWebsite: string
];

const seeds: Seed[] = [
  ["olympics-channel.global", "Olympics Channel", "GLOBAL", "English", ["Olympic sports", "Documentary", "Highlights"], "https://olympics.com/"],
  ["fifa-plus.global", "FIFA+", "GLOBAL", "Multilingual", ["Football", "Archive", "Highlights"], "https://www.plus.fifa.com/"],
  ["red-bull-tv.global", "Red Bull TV", "GLOBAL", "English", ["Motorsport", "Extreme sports", "Cycling"], "https://www.redbull.com/int-en/discover"],
  ["tubi-sports.us", "Tubi Sports", "US", "English", ["Sports documentaries", "FAST"], "https://tubitv.com/"],
  ["fox-sports.us", "FOX Sports", "US", "English", ["Football", "Baseball", "Motorsport"], "https://www.foxsports.com/"],
  ["espn.us", "ESPN", "US", "English", ["Multi-sport", "Highlights", "News"], "https://www.espn.com/"],
  ["cbs-sports.us", "CBS Sports", "US", "English", ["Football", "Basketball", "Golf"], "https://www.cbssports.com/"],
  ["nbc-sports.us", "NBC Sports", "US", "English", ["Football", "Olympic sports", "Motorsport"], "https://www.nbcsports.com/"],
  ["bleacher-report.us", "Bleacher Report", "US", "English", ["Highlights", "News", "Social video"], "https://bleacherreport.com/"],
  ["mlb.us", "MLB", "US", "English", ["Baseball"], "https://www.mlb.com/"],
  ["nba.us", "NBA", "US", "English", ["Basketball"], "https://www.nba.com/"],
  ["nfl.us", "NFL", "US", "English", ["American football"], "https://www.nfl.com/"],
  ["nhl.us", "NHL", "US", "English", ["Ice hockey"], "https://www.nhl.com/"],
  ["pga-tour.us", "PGA Tour", "US", "English", ["Golf"], "https://www.pgatour.com/"],
  ["ncaa.us", "NCAA", "US", "English", ["College sports"], "https://www.ncaa.com/"],
  ["tsn.ca", "TSN", "CA", "English", ["Multi-sport", "Hockey", "Football"], "https://www.tsn.ca/"],
  ["sportsnet.ca", "Sportsnet", "CA", "English", ["Hockey", "Baseball", "Basketball"], "https://www.sportsnet.ca/"],
  ["cbc-sports.ca", "CBC Sports", "CA", "English", ["Olympic sports", "News", "Highlights"], "https://www.cbc.ca/sports"],
  ["rds.ca", "RDS", "CA", "French", ["Hockey", "Football", "Multi-sport"], "https://www.rds.ca/"],
  ["ctv.ca", "CTV", "CA", "English", ["World Cup", "Sports news"], "https://www.ctv.ca/"],
  ["tudn.mx", "TUDN", "MX", "Spanish", ["Football", "World Cup", "Highlights"], "https://www.tudn.com/"],
  ["televisa.mx", "Televisa", "MX", "Spanish", ["Football", "World Cup", "News"], "https://www.televisa.com/"],
  ["tv-azteca.mx", "TV Azteca Deportes", "MX", "Spanish", ["Football", "Boxing", "News"], "https://www.tvazteca.com/aztecadeportes/"],
  ["marca-mx.mx", "MARCA Mexico", "MX", "Spanish", ["Football", "News", "Scores"], "https://www.marca.com/mx/"],
  ["mediotiempo.mx", "Mediotiempo", "MX", "Spanish", ["Football", "News", "Scores"], "https://www.mediotiempo.com/"],
  ["bbc-sport.gb", "BBC Sport", "GB", "English", ["Football", "Tennis", "Olympic sports"], "https://www.bbc.co.uk/sport"],
  ["itv-sport.gb", "ITV Sport", "GB", "English", ["Football", "Rugby", "Racing"], "https://www.itv.com/sport"],
  ["sky-sports.gb", "Sky Sports", "GB", "English", ["Football", "Cricket", "Formula 1"], "https://www.skysports.com/"],
  ["tnt-sports.gb", "TNT Sports", "GB", "English", ["Football", "Rugby", "Cycling"], "https://www.tntsports.co.uk/"],
  ["channel-4-sport.gb", "Channel 4 Sport", "GB", "English", ["Paralympic sports", "Formula E", "Rugby"], "https://www.channel4.com/"],
  ["rte-sport.ie", "RTE Sport", "IE", "English", ["Football", "Rugby", "GAA"], "https://www.rte.ie/sport/"],
  ["virgin-media-sport.ie", "Virgin Media Sport", "IE", "English", ["Football", "Rugby", "News"], "https://www.virginmediatelevision.ie/sport/"],
  ["france-tv-sport.fr", "France TV Sport", "FR", "French", ["Football", "Tennis", "Cycling"], "https://www.france.tv/sport/"],
  ["lequipe.fr", "L Equipe", "FR", "French", ["Football", "Cycling", "Tennis"], "https://www.lequipe.fr/"],
  ["rmc-sport.fr", "RMC Sport", "FR", "French", ["Football", "Combat sports", "News"], "https://rmcsport.bfmtv.com/"],
  ["canal-plus-sport.fr", "Canal+ Sport", "FR", "French", ["Football", "Rugby", "Motorsport"], "https://www.canalplus.com/sport/"],
  ["beinsports-fr.fr", "beIN SPORTS France", "FR", "French", ["Football", "Tennis", "Basketball"], "https://www.beinsports.com/fr-fr"],
  ["ard-sportschau.de", "Sportschau", "DE", "German", ["Football", "Winter sports", "Athletics"], "https://www.sportschau.de/"],
  ["zdf-sport.de", "ZDF Sport", "DE", "German", ["Football", "Olympic sports", "News"], "https://www.zdf.de/sport"],
  ["sport1.de", "SPORT1", "DE", "German", ["Football", "Motorsport", "Darts"], "https://www.sport1.de/"],
  ["ran.de", "ran", "DE", "German", ["Football", "American football", "Motorsport"], "https://www.ran.de/"],
  ["bild-sport.de", "BILD Sport", "DE", "German", ["Football", "News", "Scores"], "https://sportbild.bild.de/"],
  ["rtve-deportes.es", "RTVE Deportes", "ES", "Spanish", ["Football", "Cycling", "Olympic sports"], "https://www.rtve.es/deportes/"],
  ["marca.es", "MARCA", "ES", "Spanish", ["Football", "Basketball", "Motorsport"], "https://www.marca.com/"],
  ["as.es", "AS", "ES", "Spanish", ["Football", "Tennis", "Cycling"], "https://as.com/"],
  ["movistar-plus.es", "Movistar Plus Deportes", "ES", "Spanish", ["Football", "Basketball", "Motorsport"], "https://www.movistarplus.es/deportes"],
  ["sport.es", "Sport", "ES", "Spanish", ["Football", "Basketball", "News"], "https://www.sport.es/"],
  ["rai-sport.it", "Rai Sport", "IT", "Italian", ["Football", "Cycling", "Olympic sports"], "https://www.raisport.rai.it/"],
  ["sportmediaset.it", "SportMediaset", "IT", "Italian", ["Football", "Motorsport", "News"], "https://www.sportmediaset.mediaset.it/"],
  ["gazzetta.it", "La Gazzetta dello Sport", "IT", "Italian", ["Football", "Cycling", "Basketball"], "https://www.gazzetta.it/"],
  ["sky-sport-it.it", "Sky Sport Italia", "IT", "Italian", ["Football", "Formula 1", "Tennis"], "https://sport.sky.it/"],
  ["dazn-it.it", "DAZN Italia", "IT", "Italian", ["Football", "Boxing", "Multi-sport"], "https://www.dazn.com/it-IT/home"],
  ["rtp-desporto.pt", "RTP Desporto", "PT", "Portuguese", ["Football", "Futsal", "Olympic sports"], "https://www.rtp.pt/noticias/desporto"],
  ["sic-noticias-desporto.pt", "SIC Noticias Desporto", "PT", "Portuguese", ["Football", "News", "Scores"], "https://sicnoticias.pt/desporto"],
  ["record.pt", "Record", "PT", "Portuguese", ["Football", "News", "Scores"], "https://www.record.pt/"],
  ["abola.pt", "A Bola", "PT", "Portuguese", ["Football", "News", "Scores"], "https://www.abola.pt/"],
  ["nos-sport.pt", "Sport TV Portugal", "PT", "Portuguese", ["Football", "Motorsport", "Basketball"], "https://www.sporttv.pt/"],
  ["nos-sport.nl", "NOS Sport", "NL", "Dutch", ["Football", "Cycling", "Speed skating"], "https://nos.nl/sport"],
  ["ziggo-sport.nl", "Ziggo Sport", "NL", "Dutch", ["Football", "Formula 1", "Tennis"], "https://www.ziggosport.nl/"],
  ["espn-nl.nl", "ESPN Netherlands", "NL", "Dutch", ["Football", "American sports", "Highlights"], "https://www.espn.nl/"],
  ["sporza.be", "Sporza", "BE", "Dutch", ["Cycling", "Football", "Athletics"], "https://sporza.be/"],
  ["rtbf-sport.be", "RTBF Sport", "BE", "French", ["Football", "Cycling", "Tennis"], "https://www.rtbf.be/sport"],
  ["srf-sport.ch", "SRF Sport", "CH", "German", ["Football", "Skiing", "Tennis"], "https://www.srf.ch/sport"],
  ["rts-sport.ch", "RTS Sport", "CH", "French", ["Football", "Tennis", "Cycling"], "https://www.rts.ch/sport/"],
  ["orf-sport.at", "ORF Sport", "AT", "German", ["Skiing", "Football", "Formula 1"], "https://sport.orf.at/"],
  ["servus-tv-sport.at", "ServusTV Sport", "AT", "German", ["Motorsport", "Football", "Winter sports"], "https://www.servustv.com/sport/"],
  ["abc-sport.au", "ABC Sport", "AU", "English", ["Cricket", "Rugby", "AFL"], "https://www.abc.net.au/news/sport"],
  ["sbs-sport.au", "SBS Sport", "AU", "English", ["Football", "Cycling", "World Cup"], "https://www.sbs.com.au/sport"],
  ["seven-sport.au", "7plus Sport", "AU", "English", ["AFL", "Cricket", "Olympic sports"], "https://7plus.com.au/sport"],
  ["nine-sport.au", "Wide World of Sports", "AU", "English", ["Rugby", "Cricket", "Tennis"], "https://wwos.nine.com.au/"],
  ["fox-sports-au.au", "FOX Sports Australia", "AU", "English", ["Rugby", "Cricket", "Motorsport"], "https://www.foxsports.com.au/"],
  ["skysport-nz.nz", "Sky Sport NZ", "NZ", "English", ["Rugby", "Cricket", "Netball"], "https://www.skysportnow.co.nz/"],
  ["tvnz-sport.nz", "TVNZ Sport", "NZ", "English", ["Rugby", "Football", "News"], "https://www.tvnz.co.nz/shows/sport"],
  ["nhk-sports.jp", "NHK Sports", "JP", "Japanese", ["Baseball", "Football", "Olympic sports"], "https://www3.nhk.or.jp/sports/"],
  ["j-sports.jp", "J SPORTS", "JP", "Japanese", ["Baseball", "Rugby", "Motorsport"], "https://www.jsports.co.jp/"],
  ["dazn-jp.jp", "DAZN Japan", "JP", "Japanese", ["Football", "Baseball", "Motorsport"], "https://www.dazn.com/ja-JP/home"],
  ["abema-sports.jp", "ABEMA Sports", "JP", "Japanese", ["Football", "Combat sports", "Highlights"], "https://abema.tv/"],
  ["spotv-now-kr.kr", "SPOTV NOW Korea", "KR", "Korean", ["Baseball", "Football", "Basketball"], "https://www.spotvnow.co.kr/"],
  ["kbs-sports.kr", "KBS Sports", "KR", "Korean", ["Baseball", "Football", "Olympic sports"], "https://sports.kbs.co.kr/"],
  ["sbs-sports-kr.kr", "SBS Sports Korea", "KR", "Korean", ["Baseball", "Golf", "Volleyball"], "https://programs.sbs.co.kr/sports"],
  ["sony-sports.in", "Sony Sports Network", "IN", "English", ["Cricket", "Football", "Tennis"], "https://www.sonysportsnetwork.com/"],
  ["jio-sports.in", "JioCinema Sports", "IN", "English", ["Cricket", "Football", "Olympic sports"], "https://www.jiocinema.com/sports"],
  ["sports18.in", "Sports18", "IN", "English", ["Cricket", "Football", "Basketball"], "https://www.sports18.com/"],
  ["dd-sports.in", "DD Sports", "IN", "Hindi", ["Cricket", "Hockey", "Public sports"], "https://prasarbharati.gov.in/"],
  ["espn-br.br", "ESPN Brasil", "BR", "Portuguese", ["Football", "American sports", "Tennis"], "https://www.espn.com.br/"],
  ["ge-globo.br", "ge.globo", "BR", "Portuguese", ["Football", "Volleyball", "Formula 1"], "https://ge.globo.com/"],
  ["sportv-br.br", "SporTV", "BR", "Portuguese", ["Football", "Volleyball", "Motorsport"], "https://canaisglobo.globo.com/"],
  ["tntsports-br.br", "TNT Sports Brasil", "BR", "Portuguese", ["Football", "Highlights", "News"], "https://tntsports.com.br/"],
  ["tyc-sports.ar", "TyC Sports", "AR", "Spanish", ["Football", "Basketball", "Motorsport"], "https://www.tycsports.com/"],
  ["ole.ar", "Ole", "AR", "Spanish", ["Football", "News", "Scores"], "https://www.ole.com.ar/"],
  ["tntsports-ar.ar", "TNT Sports Argentina", "AR", "Spanish", ["Football", "Highlights", "News"], "https://tntsports.com.ar/"],
  ["espn-ar.ar", "ESPN Argentina", "AR", "Spanish", ["Football", "Rugby", "Tennis"], "https://www.espn.com.ar/"],
  ["tntsports-cl.cl", "TNT Sports Chile", "CL", "Spanish", ["Football", "Highlights", "News"], "https://tntsports.cl/"],
  ["adn-deportes.cl", "ADN Deportes", "CL", "Spanish", ["Football", "News", "Scores"], "https://www.adnradio.cl/deportes/"],
  ["caracol-deportes.co", "Caracol Deportes", "CO", "Spanish", ["Football", "Cycling", "News"], "https://www.caracoltv.com/deportes"],
  ["rcn-deportes.co", "RCN Deportes", "CO", "Spanish", ["Football", "Cycling", "News"], "https://www.noticiasrcn.com/deportes"],
  ["supersport.za", "SuperSport", "ZA", "English", ["Football", "Rugby", "Cricket"], "https://supersport.com/"],
  ["sabc-sport.za", "SABC Sport", "ZA", "English", ["Football", "Rugby", "Public sports"], "https://www.sabcsport.com/"],
  ["svt-sport.se", "SVT Sport", "SE", "Swedish", ["Football", "Ice hockey", "Winter sports"], "https://www.svt.se/sport/"],
  ["tv4-sport.se", "TV4 Sport", "SE", "Swedish", ["Football", "Ice hockey", "News"], "https://www.tv4.se/sport"],
  ["nrk-sport.no", "NRK Sport", "NO", "Norwegian", ["Winter sports", "Football", "Handball"], "https://www.nrk.no/sport/"],
  ["tv2-sport-no.no", "TV 2 Sport Norway", "NO", "Norwegian", ["Football", "Cycling", "Winter sports"], "https://www.tv2.no/sport/"],
  ["dr-sporten.dk", "DR Sporten", "DK", "Danish", ["Football", "Handball", "Cycling"], "https://www.dr.dk/sporten"],
  ["tv2-sport-dk.dk", "TV 2 Sport Denmark", "DK", "Danish", ["Football", "Cycling", "Handball"], "https://sport.tv2.dk/"],
  ["yle-urheilu.fi", "Yle Urheilu", "FI", "Finnish", ["Ice hockey", "Winter sports", "Athletics"], "https://yle.fi/urheilu"],
  ["mtv-urheilu.fi", "MTV Urheilu", "FI", "Finnish", ["Ice hockey", "Formula 1", "Football"], "https://www.mtvuutiset.fi/urheilu"],
  ["tvp-sport.pl", "TVP Sport", "PL", "Polish", ["Football", "Volleyball", "Winter sports"], "https://sport.tvp.pl/"],
  ["polsat-sport.pl", "Polsat Sport", "PL", "Polish", ["Football", "Volleyball", "Combat sports"], "https://www.polsatsport.pl/"],
  ["trt-spor.tr", "TRT Spor", "TR", "Turkish", ["Football", "Basketball", "Public sports"], "https://www.trtspor.com.tr/"],
  ["ntv-spor.tr", "NTV Spor", "TR", "Turkish", ["Football", "Basketball", "News"], "https://www.ntvspor.net/"],
  ["bein-mena.qa", "beIN SPORTS MENA", "QA", "Arabic", ["Football", "Tennis", "Motorsport"], "https://www.beinsports.com/"],
  ["alkass.qa", "Al Kass Sports", "QA", "Arabic", ["Football", "Qatar sports", "News"], "https://www.alkass.net/"],
  ["dubai-sports.ae", "Dubai Sports", "AE", "Arabic", ["Football", "Racing", "News"], "https://www.dubaisports.ae/"],
  ["abu-dhabi-sports.ae", "Abu Dhabi Sports", "AE", "Arabic", ["Football", "Combat sports", "Racing"], "https://adsports.ae/"],
  ["ssc-sa.sa", "SSC Sports", "SA", "Arabic", ["Football", "Motorsport", "News"], "https://ssc.tv/"],
  ["riyadiya.sa", "Arriyadiyah", "SA", "Arabic", ["Football", "News", "Scores"], "https://www.arriyadiyah.com/"],
  ["cctv-sports.cn", "CCTV Sports", "CN", "Chinese", ["Olympic sports", "Football", "Table tennis"], "https://sports.cctv.com/"],
  ["qq-sports.cn", "Tencent Sports", "CN", "Chinese", ["Basketball", "Football", "News"], "https://sports.qq.com/"],
  ["sina-sports.cn", "Sina Sports", "CN", "Chinese", ["Football", "Basketball", "News"], "https://sports.sina.com.cn/"],
  ["now-sports.hk", "Now Sports", "HK", "Chinese", ["Football", "Tennis", "News"], "https://sports.now.com/"],
  ["rthk-sport.hk", "RTHK Sport", "HK", "Chinese", ["Public sports", "News", "Highlights"], "https://www.rthk.hk/"],
  ["channel-newsasia-sport.sg", "CNA Sport", "SG", "English", ["Football", "Badminton", "News"], "https://www.channelnewsasia.com/sport"],
  ["mewatch-sport.sg", "meWATCH Sport", "SG", "English", ["Public sports", "Highlights", "News"], "https://www.mewatch.sg/"],
  ["astro-arena.my", "Astro Arena", "MY", "Malay", ["Football", "Badminton", "Motorsport"], "https://www.astro.com.my/"],
  ["stadium-astro.my", "Stadium Astro", "MY", "Malay", ["Football", "Badminton", "News"], "https://www.stadiumastro.com/"],
  ["vidio-sports.id", "Vidio Sports", "ID", "Indonesian", ["Football", "Badminton", "Basketball"], "https://www.vidio.com/categories/sports"],
  ["detik-sport.id", "detikSport", "ID", "Indonesian", ["Football", "Badminton", "News"], "https://sport.detik.com/"],
  ["thairath-sport.th", "Thairath Sport", "TH", "Thai", ["Football", "Volleyball", "News"], "https://www.thairath.co.th/sport"],
  ["trueid-sports.th", "TrueID Sports", "TH", "Thai", ["Football", "Basketball", "Badminton"], "https://sport.trueid.net/"],
  ["gma-sports.ph", "GMA Sports", "PH", "English", ["Basketball", "Boxing", "Volleyball"], "https://www.gmanetwork.com/news/sports/"],
  ["onesports.ph", "One Sports", "PH", "English", ["Basketball", "Volleyball", "News"], "https://www.onesports.ph/"]
];

export const publicSportsChannels: PublicSportsChannel[] = seeds.map(
  ([id, name, country, language, sports, officialWebsite]) => ({
    id,
    name,
    country,
    language,
    sports: [...sports],
    officialWebsite,
    evidence: `Official website metadata for ${name}; verify regional availability before using any viewing path.`,
    epgId: id
  })
);
